exclude = [
    ".env,",
    ".git",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pyenv",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
]
line-length = 88
indent-width = 4
target-version = "py311"

[lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
extend-select = ["E501"]
select = [
    "ARG",      # unused arguments
    "B",        # flake8-bugbear
    "E",        # pycodestyle
    "E722",     # bare except statements
    "F",        # pyflakes
    "F401",     # remove unused imports
    "I",        # isort
    "N",        # pep8-naming
    "RUF",      # ruff
    "SIM",      # flake8-simplify
    "UP",       # pyupgrade
]
fixable = ["ALL"]
ignore = [
    "UP006",
    "UP007",
    "UP035",
]
unfixable = []

[format]
docstring-code-format = true
docstring-code-line-length = 88
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false
